/*

MODULE INFO:
- name:         Help Parser
- version:      1.3
- creator:      zekro (github.com/zekrotja)
- last edited:  2018/04/20

MODULE DESCRIPTION:
This module is just for creating an Markdown formatted file which contains 
various information about commands, which can be implemented into the
main Readme document.

*/


var Main = require('../main')
var fs = require('fs')
var cmds = Main.cmd.helplist


var categories = []

Object.keys(cmds).forEach(i => {
    let _cat = cmds[i].type
    if (categories.indexOf(_cat) == -1)
        categories.push(_cat)
})

var output = '# Commands\n'
var head = '# Commands index\n'

categories.forEach(category => {

    head += `\n### ${category}\n\n`
    output += `\n## ${category}\n\n`

    Object.keys(cmds)
        .filter(i => cmds[i].type == category)
        .forEach(i => {

            let c = cmds[i]
            let help = c.help.replace(/`/g, '')

            head += `- [${i}](https://github.com/zekroTJA/zekroBot2/wiki/Commands#${i})\n`

            output += `### ${i}\n\n` +
                `> ${c.description}\n\n` +
                '| | |\n' +
                '| --------- | --------- |\n' +
                `| Permission | ${c.perm} |\n` +
                `| Group | ${c.type} |\n` +
                `| Aliases | ${c.aliases.join(', ')} |\n\n` +
                '**Usage**\n\n' +
                '```php\n' +
                help +
                '```\n\n\n'

        })
})

output = '> This content is automatically generated by zekroBot2.\n\n---\n\n' + head + '\n\n---\n\n' + output

fs.writeFile('/var/www/html/files/zbcmds.md', output)